apiVersion: apps/v1
kind: Deployment
metadata:
  name: drrfeg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drrfeg
  template:
    metadata:
      labels:
        app: drrfeg
    spec:
      containers:
      - image: okteto.dev/drrfeg:latest
        name: drrfeg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b096927a-a21f-4b46-aac9-8ab37b007327"
        - name: Vless_Path
          value: "/vl55you5"
        - name: Vmess_UUID
          value: "b096927a-a21f-4b46-aac9-8ab37b007327"
        - name: Vmess_Path
          value: "/vm6me66"
        - name: Share_Path
          value: "/v2link"
